### ISSUE TITLE
New update of Beijing Subway

### ISSUE THREAD

**Issue by AnDanJuneUnderline** [wongchito/RailMapGenerator#144] opened 2021-10-08 00:04 UTC
I made it during the National Day XD
[bjsubway-oct5th.zip](https://github.com/wongchito/RailMapGenerator/files/7307540/bjsubway-oct5th.zip)

**Comment by AnDanJuneUnderline** [comment] 2021-10-08 07:47
[map.json.bjline6.zip](https://github.com/wongchito/RailMapGenerator/files/7309398/map.json.bjline6.zip)
By the way, There was a bug when I made Line 6. thx

**Comment by AnDanJuneUnderline** [comment] 2021-10-08 22:55
I'm sorry, because after the bug was found in the template of Line 6, I checked all the templates again and adapted them to the style of MTR. Please understand the inconvenience caused to you ;(
[repeatbjsubway-oct9th.zip](https://github.com/wongchito/RailMapGenerator/files/7314546/repeatbjsubway-oct9th.zip)

**Comment by thekingofcity** [comment] 2021-10-09 15:37
Hi, thanks for the contribution. Since adding so many templates takes a lot of time, we may fix this when we are not so busy.

Or you could take a look at bfda99 and 65f622 on how to add them to the project and submit a pull request😁

**Comment by AnDanJuneUnderline** [comment] 2021-10-10 05:16
ok i will try =)

**Comment by AnDanJuneUnderline** [comment] 2021-11-02 23:26
I found a way to create a pull request but I didn't how to add my templates and make it work ;(

**Comment by thekingofcity** [comment] 2021-11-03 16:04
Hi, I do realize there is difficulty for contributors who come from non programming background.

Could you wait another two days so that I’m able to update the [Wiki on how to add line templates](https://github.com/wongchito/RailMapGenerator/wiki/How-to-add-colors-list-or-line-templates).

The basic idea is that it is possible to copy and paste a code template and paste the text file in the comments here. See #151 for a recent example.

**Comment by AnDanJuneUnderline** [comment] 2021-11-03 22:04
OK. Thanks a lot :)

**Comment by thekingofcity** [comment] 2021-11-05 09:14
Hi, [Wiki on how to add line templates](https://github.com/wongchito/RailMapGenerator/wiki/How-to-add-color-palette-or-line-templates) is updated. You can now have a try and comment if you encounter any problems.

**Comment by AnDanJuneUnderline** [comment] 2021-11-06 10:11
I see. I will read it carefully if I am free tomorrow.
As an aside, I can't open the information column in the website when I use my mobile phone. If I should open a new issue, please tell me.😄

**Comment by thekingofcity** [comment] 2021-11-06 11:12
> As an aside, I can't open the information column in the website when I use my mobile phone. If I should open a new issue, please tell me.😄

Is it possible to provide more details such as the screenshot where the information column is missing?

**Comment by AnDanJuneUnderline** [comment] 2021-11-07 09:19
https://user-images.githubusercontent.com/89013535/140639354-f2dc955f-5b30-4d02-ae16-e4f87da7a156.mp4

I think I should send you a video...

**Comment by thekingofcity** [comment] 2021-11-07 15:05
It's not reproducible on my device, would you like to switch to Chrome or Firefox for another check?

**Comment by AnDanJuneUnderline** [comment] 2021-11-07 21:27
It can be opened on the computer. But, only Firefox can open it on the mobile phone.

**Comment by thekingofcity** [comment] 2021-11-08 02:54
Chrome on Android won't work?

**Comment by AnDanJuneUnderline** [comment] 2021-11-08 03:50
Yes... It didn't work on my phone at least.

**Comment by thekingofcity** [comment] 2021-11-08 06:53
Well, since neither do I or another core contributor has an Android device, it seems quite impossible to reproduce and fix the problem. We have to leave it in pending status.

**Comment by AnDanJuneUnderline** [comment] 2021-11-08 13:02
Okay, I know.

**Comment by AnDanJuneUnderline** [comment] 2021-11-09 05:40
[bjsubway.zip](https://github.com/wongchito/RailMapGenerator/files/7502218/bjsubway.zip)
Did I finish it perfectly...?

**Comment by thekingofcity** [comment] 2021-11-09 06:14
Hi, I checked some of them and they look exactly what the Wiki requires. Besides, for those lines that are added for the first time, a name and its translation are needed. See the 7th step of [Wiki](https://github.com/wongchito/RailMapGenerator/wiki/How-to-add-color-palette-and-line-templates#line-templates) for more details.

**Comment by AnDanJuneUnderline** [comment] 2021-11-09 07:06
`bjsubway: [
        {
            filename: 'bj1',
            name: {
                en: 'Line 1 by AnDanJuneUnderline',
                'zh-Hans': '1号线 来自 AnDanJuneUnderline',
                'zh-Hant': '1號線 來自 AnDanJuneUnderline',
            },
        },
        {
            filename: 'bj4',
            name: {
                en: 'Line 4 by AnDanJuneUnderline',
                'zh-Hans': '4号线 来自 AnDanJuneUnderline',
                'zh-Hant': '4號線 來自 AnDanJuneUnderline',
            },
        },
        {
            filename: 'bj5',
            name: {
                en: 'Line 5 by AnDanJuneUnderline',
                'zh-Hans': '5号线 来自 AnDanJuneUnderline',
                'zh-Hant': '5號線 來自 AnDanJuneUnderline',
            },
        },
        {
            filename: 'bj6',
            name: {
                en: 'Line 6 by AnDanJuneUnderline',
                'zh-Hans': '6号线 来自 AnDanJuneUnderline',
                'zh-Hant': '6號線 來自 AnDanJuneUnderline',
            },
        },
        {
            filename: 'bj7',
            name: {
                en: 'Line 7 by AnDanJuneUnderline',
                'zh-Hans': '7号线 来自 AnDanJuneUnderline',
                'zh-Hant': '7號線 來自 AnDanJuneUnderline',
            },
        },
        {
            filename: 'bj9',
            name: {
                en: 'Line 9 by AnDanJuneUnderline',
                'zh-Hans': '9号线 来自 AnDanJuneUnderline',
                'zh-Hant': '9號線 來自 AnDanJuneUnderline',
            },
        },
        {
            filename: 'bj13',
            name: {
                en: 'Line 13 by AnDanJuneUnderline',
                'zh-Hans': '13号线 来自 AnDanJuneUnderline',
                'zh-Hant': '13號線 來自 AnDanJuneUnderline',
            },
        },
        {
            filename: 'yzl',
            name: {
                en: 'Yizhuang Line by AnDanJuneUnderline',
                'zh-Hans': '亦庄线 来自 AnDanJuneUnderline',
                'zh-Hant': '亦莊線 來自 AnDanJuneUnderline',
            },
        },
        {
            filename: 't1l',
            name: {
                en: 'Yizhuang T1 Line by AnDanJuneUnderline',
                'zh-Hans': '亦庄T1线 来自 AnDanJuneUnderline',
                'zh-Hant': '亦莊T1線 來自 AnDanJuneUnderline',
            },
        },`
Like this?

**Comment by AnDanJuneUnderline** [comment] 2021-11-09 07:16
bjsubway: [ { filename: 'bj1', name: { en: 'Line 1 by AnDanJuneUnderline', 'zh-Hans': '1号线 来自 AnDanJuneUnderline', 'zh-Hant': '1號線 來自 AnDanJuneUnderline', }, }, { filename: 'bj4', name: { en: 'Line 4 by AnDanJuneUnderline', 'zh-Hans': '4号线 来自 AnDanJuneUnderline', 'zh-Hant': '4號線 來自 AnDanJuneUnderline', }, }, { filename: 'bj5', name: { en: 'Line 5 by AnDanJuneUnderline', 'zh-Hans': '5号线 来自 AnDanJuneUnderline', 'zh-Hant': '5號線 來自 AnDanJuneUnderline', }, }, { filename: 'bj6', name: { en: 'Line 6 by AnDanJuneUnderline', 'zh-Hans': '6号线 来自 AnDanJuneUnderline', 'zh-Hant': '6號線 來自 AnDanJuneUnderline', }, }, { filename: 'bj7', name: { en: 'Line 7 by AnDanJuneUnderline', 'zh-Hans': '7号线 来自 AnDanJuneUnderline', 'zh-Hant': '7號線 來自 AnDanJuneUnderline', }, }, { filename: 'bj9', name: { en: 'Line 9 by AnDanJuneUnderline', 'zh-Hans': '9号线 来自 AnDanJuneUnderline', 'zh-Hant': '9號線 來自 AnDanJuneUnderline', }, }, { filename: 'bj13', name: { en: 'Line 13 by AnDanJuneUnderline', 'zh-Hans': '13号线 来自 AnDanJuneUnderline', 'zh-Hant': '13號線 來自 AnDanJuneUnderline', }, }, { filename: 'yzl', name: { en: 'Yizhuang Line by AnDanJuneUnderline', 'zh-Hans': '亦庄线 来自 AnDanJuneUnderline', 'zh-Hant': '亦莊線 來自 AnDanJuneUnderline', }, }, { filename: 't1l', name: { en: 'Yizhuang T1 Line by AnDanJuneUnderline', 'zh-Hans': '亦庄T1线 来自 AnDanJuneUnderline', 'zh-Hant': '亦莊T1線 來自 AnDanJuneUnderline', }, }, ],

Like this?
Oh... My website deleted some spaces and tabs... Should I give it to you another way?

**Comment by thekingofcity** [comment] 2021-11-09 13:49
Hi, they are great, and would be better if they have the right format. 😀
Anyway, I added them in 7bd28bb3 and will be released in 3.10.3.

**Closed by thekingofcity** 2021-11-09 13:49 UTC
Labels: enhancement
