### ISSUE TITLE
Unable to change wide of "Station nameplate width" and "Width of circuit diagram".

### ISSUE THREAD

**Issue by xiaobaimao233** [wongchito/RailMapGenerator#131] opened 2021-09-11 13:11 UTC
When I type the number value of it, it dosen't show, and when I want to delete the value, the old value can't delete and I can't type the new value, I hope the author will fix this problem, thanks.

**Comment by wongchito** [comment] 2021-09-12 04:51
Hi all,

We're investigating the root cause of this issue. We've released a quick fix for it but it's not perfectly solved the issue. We'll back to you soon with the proper fix.

Sorry for the inconvenience and thank you for using RMG.

**Comment by wongchito** [comment] 2022-01-03 06:23
Fixed in #206

**Closed by wongchito** 2022-01-03 06:23 UTC
Labels: bug
