### ISSUE TITLE
下載時字體錯誤

### ISSUE THREAD

**Issue by siumingdecade** [wongchito/RailMapGenerator#179] opened 2021-11-16 14:17 UTC
你好，我之前曾經回報線上產生器的港鐵界面字體變幼（而下載為正常的思源宋體），現在出現了線上界面字體正確，但是下載時字體會變幼的情況，煩請修正，謝謝

**Comment by thekingofcity** [comment] 2021-11-17 02:36
Is this caused by [this line](https://github.com/wongchito/RailMapGenerator/blob/master/src/panels/save/export-diag/mtr-helper.ts#L66)?

PS: this should be fixed after #125 is merged as that PR also touches some part of the download process.

**Closed** 2021-11-17 15:05 UTC
Labels: bug
